### ISSUE TITLE
Not working with v-leaflet 1.0.0-b2

### ISSUE THREAD

**Issue by russellhoff** [octavm/v-leaflet-shramov-parent#7]
I've updated recently vaadin to 7.5.6 and v-leaflet addon to the latest version 1.0.0-b2. Unfortunately, v-leaflet-shramov-parent doesn't work (version 0.0.3): when the map is shown on screen, the map remains blank.

![shramov-error](https://cloud.githubusercontent.com/assets/1479066/10067661/a448f378-629e-11e5-86b0-09f4fbf3d798.png)

Do you know how to solve it? Thanks!

**Comment by mstahv** [comment]
Yes. Would probably work by trying to build against leaflet_one branch: https://github.com/shramov/leaflet-plugins/tree/leaflet_one

So practically building the leaflet_one branch of the js project, updating the js in GWT wrapper and building new vaadin version agains it. Might need some minor changes in vaadin integration code as well, but I guess this would be quite easy to do. Want to try creating a pull request?

**Comment by russellhoff** [comment]
Sure, let me do it tomorrow ;).

Btw, I'm getting an error in v-leaflet with the latest vaadin version 7.5.6: when hovering a marker, I'm getting an error (can't paste it since I've downgraded vaadin to 7.5.2 and now the error has disappeared). Tomorrow I'll compile it with 7.5.6 and I'll tell u exactly. I guess there is some incompatibility between vaadin 7.5.6 and v-leaflet (using 0.6.4, previous version of 1.0.0-b1).

See you!

**Comment by mstahv** [comment]
Thanks in advance!

Let me also know about the details of the other issue in v-leaflet project. I'm putting my efforts currently on 1.0 series, but building a 0.6.5 is not an issue either.

**Comment by russellhoff** [comment]
Good morning @mstahv. So, to build a new version of v-leaflet-shramov I must:

1) Build leaflet_one branch of the JS project (I guess you mean building this https://github.com/shramov/leaflet-plugins/tree/leaflet_one).
2) Update g-leaflet-shramov with the new JS built on 1) (but how can I achieve that? I don't know it, I need any clue).
3) Update v-leaflet-shramov with the new g-leaflet-shramov. This would require, probably, some minor changes as you told me.

I need some clues regarding the building proccess of the JS and its integration with the GWT wrapper... Sorry and thank you! 

PS: I'm gonna update vaadin to the latest version, check the error, take some screenshots and post them to you.

**Comment by russellhoff** [comment]
V-leaflet problem:

![vleaflet-error-marker](https://cloud.githubusercontent.com/assets/1479066/10094963/1578978e-6366-11e5-8842-55951a66a4fb.png)

Stack trace:

```
712612ms    Server to client RPC call: 256:org.vaadin.addon.leaflet.shared.ILayerClientRpc.bringToFront([])
```

712618ms    Error performing server to client RPC callscom.google.gwt.core.client.JavaScriptException: (TypeError) : a.bringToFront is not a function
   at Unknown.Ame(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.Vsc(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.EFc(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.T5b(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.V5b(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.GUb(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.FUb(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.RTb(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.PTb(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.B4b(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.eval(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.lp(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.op(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown.eval(com.ingartek.cavwebapp.view.widgetset.CavwebappWidgetset-0.js)
   at Unknown._f(http://localhost:9090/cavwebapp/VAADIN/vaadinPush.debug.js?v=7.5.6)
   at Unknown._invokeFunction(http://localhost:9090/cavwebapp/VAADIN/vaadinPush.debug.js?v=7.5.6)
   at Unknown._invokeCallback(http://localhost:9090/cavwebapp/VAADIN/vaadinPush.debug.js?v=7.5.6)
   at Unknown._websocket.onmessage(http://localhost:9090/cavwebapp/VAADIN/vaadinPush.debug.js?v=7.5.6)
712665ms    \* Unregistered 0 connectors

**Comment by mstahv** [comment]
Hi,

It might actually be enough to copy this https://github.com/shramov/leaflet-plugins/blob/leaflet_one/layer/tile/Google.js to https://github.com/mstahv/v-leaflet-shramov-parent/blob/master/g-leaflet-shramov/src/main/resources/org/peimari/gleaflet/client/resources/Google.js

Then you change it so that the pom.xml in vaadin integration points to development version of gwt integration. Upgrade the gwt projects version to next minor with "-SNAPSHOT" qualifier and use the same in GWT version.

Then issuing mvn install from top level should generate you a development build to your local maven repository for testing.

The Vaadin 7.5.6 issue sounds really weird and should be investigated. Would you add a ticket to v-leaflet project about this. If it is only update of Vaadin that causes it, it might be critical regression in Vaadin.

cheers,
matti

**Comment by russellhoff** [comment]
Sure, I'm gonna open a new ticket.

I'm currently testing the shramov update locally.

**Comment by russellhoff** [comment]
When doing "mvn -X install" I get the following error:

]] failed with status 1
        at org.codehaus.mojo.gwt.shell.AbstractGwtShellMojo$JavaCommand.execute(AbstractGwtShellMojo.java:497)
        at org.codehaus.mojo.gwt.shell.CompileMojo.compile(CompileMojo.java:366)
        at org.codehaus.mojo.gwt.shell.CompileMojo.doExecute(CompileMojo.java:281)
        at org.codehaus.mojo.gwt.shell.AbstractGwtShellMojo.execute(AbstractGwtShellMojo.java:172)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :v-leaflet-shramov

This error is a result of compiling v-leaflet-shramov

**Comment by russellhoff** [comment]
Sorry for my huge delay... I've been busy in here.
